language: cpp
compiler: g++
branches:
  only:
  - master
before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq python3
- sudo apt-get install -qq libsfml-dev
- sudo apt-get install -qq gcc
- sudo apt-get install -qq g++
script:
- make -f makefiles/make.unix
- bin/Debug/main